@echo off
setlocal

:: Ask the user for number of images
set /p numImages="Enter the number of images you want to generate: "

:: Ask the user if they want a random prompt
set /p randomPrompt="Do you want a random prompt? (yes/no): "

if /i "%randomPrompt%"=="yes" (
    call :generateRandomPrompt
) else (
    set /p userPrompt="Enter your custom prompt: "
    set finalPrompt=%userPrompt%
)

:: Run the Python command
python demo.py --device GPU --prompt "%finalPrompt%" --output "GeneratedImage.png" --num-inference-steps 32 --num-images %numImages%

:: Exit the batch script
exit /b

:: Function to generate a random prompt based on keywords
:generateRandomPrompt
:: Randomly choose a subject
set /a rndChoice1=%random% %% 102
if %rndChoice1%==0 (set subject=skater girl)
if %rndChoice1%==1 (set subject=beach)
if %rndChoice1%==2 (set subject=forest)
if %rndChoice1%==3 (set subject=mountains)
if %rndChoice1%==4 (set subject=cityscape)
if %rndChoice1%==5 (set subject=sunrise)
if %rndChoice1%==6 (set subject=sunset)
if %rndChoice1%==7 (set subject=waterfall)
if %rndChoice1%==8 (set subject=lighthouse)
if %rndChoice1%==9 (set subject=night sky)
if %rndChoice1%==10 (set subject=desert)
if %rndChoice1%==11 (set subject=flower garden)
if %rndChoice1%==12 (set subject=abandoned building)
if %rndChoice1%==13 (set subject=countryside)
if %rndChoice1%==14 (set subject=ocean)
if %rndChoice1%==15 (set subject=rainforest)
if %rndChoice1%==16 (set subject=snow-capped mountains)
if %rndChoice1%==17 (set subject=bridge)
if %rndChoice1%==18 (set subject=ancient ruins)
if %rndChoice1%==19 (set subject=foggy landscape)
if %rndChoice1%==20 (set subject=wheat field)
if %rndChoice1%==21 (set subject=waterfront)
if %rndChoice1%==22 (set subject=castle)
if %rndChoice1%==23 (set subject=cave)
if %rndChoice1%==24 (set subject=coffee shop)
if %rndChoice1%==25 (set subject=rainy day)
if %rndChoice1%==26 (set subject=carnival)
if %rndChoice1%==27 (set subject=farm)
if %rndChoice1%==28 (set subject=iceberg)
if %rndChoice1%==29 (set subject=downtown)
if %rndChoice1%==30 (set subject=vineyard)
if %rndChoice1%==31 (set subject=sailor girl)
if %rndChoice1%==32 (set subject=cyberpunk city)
if %rndChoice1%==33 (set subject=haunted house)
if %rndChoice1%==34 (set subject=snowy village)
if %rndChoice1%==35 (set subject=water city)
if %rndChoice1%==36 (set subject=space station)
if %rndChoice1%==37 (set subject=samurai warrior)
if %rndChoice1%==38 (set subject=steampunk world)
if %rndChoice1%==39 (set subject=underwater city)
if %rndChoice1%==40 (set subject=enchanted forest)
if %rndChoice1%==41 (set subject=mecha battle)
if %rndChoice1%==42 (set subject=futuristic city)
if %rndChoice1%==43 (set subject=schoolgirl)
if %rndChoice1%==44 (set subject=fantasy castle)
if %rndChoice1%==45 (set subject=post-apocalyptic)
if %rndChoice1%==46 (set subject=superhero)
if %rndChoice1%==47 (set subject=wizard academy)
if %rndChoice1%==48 (set subject=beach resort)
if %rndChoice1%==49 (set subject=magical girl)
if %rndChoice1%==50 (set subject=fairy tale)
if %rndChoice1%==51 (set subject=fantasy town)
if %rndChoice1%==52 (set subject=gothic cathedral)
if %rndChoice1%==53 (set subject=summer festival)
if %rndChoice1%==54 (set subject=sci-fi city)
if %rndChoice1%==55 (set subject=warrior princess)
if %rndChoice1%==56 (set subject=jungle adventure)
if %rndChoice1%==57 (set subject=dystopian future)
if %rndChoice1%==58 (set subject=time travel)
if %rndChoice1%==59 (set subject=cyborg girl)
if %rndChoice1%==60 (set subject=space explorer)
if %rndChoice1%==61 (set subject=digital world)
if %rndChoice1%==62 (set subject=fantasy market)
if %rndChoice1%==63 (set subject=dragon rider)
if %rndChoice1%==64 (set subject=pirate ship)
if %rndChoice1%==65 (set subject=angelic realm)
if %rndChoice1%==66 (set subject=neon city)
if %rndChoice1%==67 (set subject=futuristic robot)
if %rndChoice1%==68 (set subject=wizard's tower)
if %rndChoice1%==69 (set subject=cyber girl)
if %rndChoice1%==70 (set subject=ghostly mansion)
if %rndChoice1%==71 (set subject=steampunk airship)
if %rndChoice1%==72 (set subject=fairy kingdom)
if %rndChoice1%==73 (set subject=vampire castle)
if %rndChoice1%==74 (set subject=high-tech school)
if %rndChoice1%==75 (set subject=forest spirit)
if %rndChoice1%==76 (set subject=underground city)
if %rndChoice1%==77 (set subject=moonlit night)
if %rndChoice1%==78 (set subject=robotic cityscape)
if %rndChoice1%==79 (set subject=magical library)
if %rndChoice1%==80 (set subject=meadow of flowers)
if %rndChoice1%==81 (set subject=knight's quest)
if %rndChoice1%==82 (set subject=galactic empire)
if %rndChoice1%==83 (set subject=mermaid lagoon)
if %rndChoice1%==84 (set subject=cyberpunk gang)
if %rndChoice1%==85 (set subject=enchanted lake)
if %rndChoice1%==86 (set subject=space battle)
if %rndChoice1%==87 (set subject=mystic cave)
if %rndChoice1%==88 (set subject=futuristic subway)
if %rndChoice1%==89 (set subject=angel vs. demon)
if %rndChoice1%==90 (set subject=witch's hut)
if %rndChoice1%==91 (set subject=virtual reality)
if %rndChoice1%==92 (set subject=samurai duel)
if %rndChoice1%==93 (set subject=futuristic skyscrapers)
if %rndChoice1%==94 (set subject=wizard's spell)
if %rndChoice1%==95 (set subject=magical marketplace)
if %rndChoice1%==96 (set subject=cyberpunk cafe)
if %rndChoice1%==97 (set subject=dreamscape)
if %rndChoice1%==98 (set subject=underwater adventure)
if %rndChoice1%==99 (set subject=space colony)
if %rndChoice1%==100 (set subject=robot uprising)
if %rndChoice1%==101 (set subject=fantasy airship)
if %rndChoice1%==102 (set subject=haunted forest)

:: Randomly choose an adjective
set /a rndChoice2=%random% %% 103

if %rndChoice2%==0 (set adjective=cool)
if %rndChoice2%==1 (set adjective=sunny)
if %rndChoice2%==2 (set adjective=mystical)
if %rndChoice2%==3 (set adjective=brilliant)
if %rndChoice2%==4 (set adjective=sparkling)
if %rndChoice2%==5 (set adjective=wondrous)
if %rndChoice2%==6 (set adjective=majestic)
if %rndChoice2%==7 (set adjective=radiant)
if %rndChoice2%==8 (set adjective=vibrant)
if %rndChoice2%==9 (set adjective=enchanting)
if %rndChoice2%==10 (set adjective=captivating)
if %rndChoice2%==11 (set adjective=charming)
if %rndChoice2%==12 (set adjective=glorious)
if %rndChoice2%==13 (set adjective=fantastic)
if %rndChoice2%==14 (set adjective=marvelous)
if %rndChoice2%==15 (set adjective=exquisite)
if %rndChoice2%==16 (set adjective=delightful)
if %rndChoice2%==17 (set adjective=breathtaking)
if %rndChoice2%==18 (set adjective=stunning)
if %rndChoice2%==19 (set adjective=mesmerizing)
if %rndChoice2%==20 (set adjective=fascinating)
if %rndChoice2%==21 (set adjective=enigmatic)
if %rndChoice2%==22 (set adjective=magical)
if %rndChoice2%==23 (set adjective=fantastical)
if %rndChoice2%==24 (set adjective=wonderous)
if %rndChoice2%==25 (set adjective=ravishing)
if %rndChoice2%==26 (set adjective=glamorous)
if %rndChoice2%==27 (set adjective=dazzling)
if %rndChoice2%==28 (set adjective=resplendent)
if %rndChoice2%==29 (set adjective=spectacular)
if %rndChoice2%==30 (set adjective=gorgeous)
if %rndChoice2%==31 (set adjective=magnificent)
if %rndChoice2%==32 (set adjective=grand)
if %rndChoice2%==33 (set adjective=splendid)
if %rndChoice2%==34 (set adjective=brilliant)
if %rndChoice2%==35 (set adjective=glowing)
if %rndChoice2%==36 (set adjective=beaming)
if %rndChoice2%==37 (set adjective=shining)
if %rndChoice2%==38 (set adjective=effervescent)
if %rndChoice2%==39 (set adjective=gleaming)
if %rndChoice2%==40 (set adjective=radiant)
if %rndChoice2%==41 (set adjective=luminous)
if %rndChoice2%==42 (set adjective=vivid)
if %rndChoice2%==43 (set adjective=dazzling)
if %rndChoice2%==44 (set adjective=glimmering)
if %rndChoice2%==45 (set adjective=twinkling)
if %rndChoice2%==46 (set adjective=scintillating)
if %rndChoice2%==47 (set adjective=brilliant)
if %rndChoice2%==48 (set adjective=mesmerizing)
if %rndChoice2%==49 (set adjective=bewitching)
if %rndChoice2%==50 (set adjective=enchanting)
if %rndChoice2%==51 (set adjective=captivating)
if %rndChoice2%==52 (set adjective=alluring)
if %rndChoice2%==53 (set adjective=entrancing)
if %rndChoice2%==54 (set adjective=charming)
if %rndChoice2%==55 (set adjective=spellbinding)
if %rndChoice2%==56 (set adjective=transfixing)
if %rndChoice2%==57 (set adjective=magnetic)
if %rndChoice2%==58 (set adjective=hypnotic)
if %rndChoice2%==59 (set adjective=irresistible)
if %rndChoice2%==60 (set adjective=stunning)
if %rndChoice2%==61 (set adjective=awe-inspiring)
if %rndChoice2%==62 (set adjective=breathtaking)
if %rndChoice2%==63 (set adjective=awe-striking)
if %rndChoice2%==64 (set adjective=impressive)
if %rndChoice2%==65 (set adjective=sublime)
if %rndChoice2%==66 (set adjective=mind-blowing)
if %rndChoice2%==67 (set adjective=mind-boggling)
if %rndChoice2%==68 (set adjective=extraordinary)
if %rndChoice2%==69 (set adjective=fantastic)
if %rndChoice2%==70 (set adjective=marvelous)
if %rndChoice2%==71 (set adjective=excellent)
if %rndChoice2%==72 (set adjective=outstanding)
if %rndChoice2%==73 (set adjective=superb)
if %rndChoice2%==74 (set adjective=remarkable)
if %rndChoice2%==75 (set adjective=exceptional)
if %rndChoice2%==76 (set adjective=phenomenal)
if %rndChoice2%==77 (set adjective=wonderful)
if %rndChoice2%==78 (set adjective=terrific)
if %rndChoice2%==79 (set adjective=incredible)
if %rndChoice2%==80 (set adjective=amazing)
if %rndChoice2%==81 (set adjective=astonishing)
if %rndChoice2%==82 (set adjective=mind-blowing)
if %rndChoice2%==83 (set adjective=astounding)
if %rndChoice2%==84 (set adjective=awe-inspiring)
if %rndChoice2%==85 (set adjective=jaw-dropping)
if %rndChoice2%==86 (set adjective=unbelievable)
if %rndChoice2%==87 (set adjective=mesmerizing)
if %rndChoice2%==88 (set adjective=stupendous)
if %rndChoice2%==89 (set adjective=fascinating)
if %rndChoice2%==90 (set adjective=enchanting)
if %rndChoice2%==91 (set adjective=captivating)
if %rndChoice2%==92 (set adjective=charming)
if %rndChoice2%==93 (set adjective=spellbinding)
if %rndChoice2%==94 (set adjective=irresistible)
if %rndChoice2%==95 (set adjective=bewitching)
if %rndChoice2%==96 (set adjective=entrancing)
if %rndChoice2%==97 (set adjective=alluring)
if %rndChoice2%==98 (set adjective=hypnotic)
if %rndChoice2%==99 (set adjective=enigmatic)
if %rndChoice2%==100 (set adjective=mysterious)
if %rndChoice2%==101 (set adjective=spellbound)
if %rndChoice2%==102 (set adjective=magical)

:: Randomly choose a style
set /a rndChoice3=%random% %% 103
if %rndChoice3%==0 (set style=with gothic styles)
if %rndChoice3%==1 (set style=with palm trees)
if %rndChoice3%==2 (set style=with glowing creatures)
if %rndChoice3%==3 (set style=with futuristic cityscape)
if %rndChoice3%==4 (set style=with underwater scenery)
if %rndChoice3%==5 (set style=with steampunk elements)
if %rndChoice3%==6 (set style=with celestial bodies)
if %rndChoice3%==7 (set style=with enchanted forest)
if %rndChoice3%==8 (set style=with cyberpunk city)
if %rndChoice3%==9 (set style=with ancient ruins)
if %rndChoice3%==10 (set style=with floating islands)
if %rndChoice3%==11 (set style=with cherry blossoms)
if %rndChoice3%==12 (set style=with dreamlike atmosphere)
if %rndChoice3%==13 (set style=with snow-capped mountains)
if %rndChoice3%==14 (set style=with wildflower meadows)
if %rndChoice3%==15 (set style=with lunar landscape)
if %rndChoice3%==16 (set style=with rainbow-colored sky)
if %rndChoice3%==17 (set style=with bustling marketplace)
if %rndChoice3%==18 (set style=with dragon-infested mountains)
if %rndChoice3%==19 (set style=with candy-colored world)
if %rndChoice3%==20 (set style=with haunted castle)
if %rndChoice3%==21 (set style=with alien planets)
if %rndChoice3%==22 (set style=with time-traveling theme)
if %rndChoice3%==23 (set style=with ancient civilization)
if %rndChoice3%==24 (set style=with fire and lava)
if %rndChoice3%==25 (set style=with underwater city)
if %rndChoice3%==26 (set style=with magical library)
if %rndChoice3%==27 (set style=with ice sculptures)
if %rndChoice3%==28 (set style=with zen garden)
if %rndChoice3%==29 (set style=with psychedelic art)
if %rndChoice3%==30 (set style=with rainforest)
if %rndChoice3%==31 (set style=with alien invasion)
if %rndChoice3%==32 (set style=with ancient temples)
if %rndChoice3%==33 (set style=with post-apocalyptic city)
if %rndChoice3%==34 (set style=with enchanted sea)
if %rndChoice3%==35 (set style=with magical carnival)
if %rndChoice3%==36 (set style=with moonlit night)
if %rndChoice3%==37 (set style=with lost civilization)
if %rndChoice3%==38 (set style=with floating market)
if %rndChoice3%==39 (set style=with futuristic skyscrapers)
if %rndChoice3%==40 (set style=with desert oasis)
if %rndChoice3%==41 (set style=with haunted forest)
if %rndChoice3%==42 (set style=with mythological creatures)
if %rndChoice3%==43 (set style=with candyland)
if %rndChoice3%==44 (set style=with mountain monasteries)
if %rndChoice3%==45 (set style=with underwater caves)
if %rndChoice3%==46 (set style=with floating castle)
if %rndChoice3%==47 (set style=with ancient legends)
if %rndChoice3%==48 (set style=with cybernetic organisms)
if %rndChoice3%==49 (set style=with celestial gardens)
if %rndChoice3%==50 (set style=with ice age)
if %rndChoice3%==51 (set style=with futuristic transportation)
if %rndChoice3%==52 (set style=with mystical portals)
if %rndChoice3%==53 (set style=with bioluminescent forest)
if %rndChoice3%==54 (set style=with floating waterfalls)
if %rndChoice3%==55 (set style=with parallel dimensions)
if %rndChoice3%==56 (set style=with ancient tree of life)
if %rndChoice3%==57 (set style=with stormy seascape)
if %rndChoice3%==58 (set style=with intergalactic travel)
if %rndChoice3%==59 (set style=with futuristic robots)
if %rndChoice3%==60 (set style=with enchanted cave)
if %rndChoice3%==61 (set style=with neon-lit metropolis)
if %rndChoice3%==62 (set style=with lost in time)
if %rndChoice3%==63 (set style=with mythical water creatures)
if %rndChoice3%==64 (set style=with floating gardens)
if %rndChoice3%==65 (set style=with enchanted waterfalls)
if %rndChoice3%==66 (set style=with alien wildlife)
if %rndChoice3%==67 (set style=with magical rain)
if %rndChoice3%==68 (set style=with ancient cave paintings)
if %rndChoice3%==69 (set style=with futuristic amusement park)
if %rndChoice3%==70 (set style=with enchanted moonlight)
if %rndChoice3%==71 (set style=with mystical mountains)
if %rndChoice3%==72 (set style=with cyber cityscape)
if %rndChoice3%==73 (set style=with underwater metropolis)
if %rndChoice3%==74 (set style=with jungle ruins)
if %rndChoice3%==75 (set style=with mythical floating islands)
if %rndChoice3%==76 (set style=with neon wilderness)
if %rndChoice3%==77 (set style=with ancient stargate)
if %rndChoice3%==78 (set style=with robotic wildlife)
if %rndChoice3%==79 (set style=with celestial observatory)
if %rndChoice3%==80 (set style=with icy tundra)
if %rndChoice3%==81 (set style=with futuristic underwater transportation)
if %rndChoice3%==82 (set style=with enchanted ruins)
if %rndChoice3%==83 (set style=with floating cities)
if %rndChoice3%==84 (set style=with dreamy clouds)
if %rndChoice3%==85 (set style=with mythical forest creatures)
if %rndChoice3%==86 (set style=with magical floating castle)
if %rndChoice3%==87 (set style=with lost spaceship)
if %rndChoice3%==88 (set style=with bioluminescent sea creatures)
if %rndChoice3%==89 (set style=with alien sky)
if %rndChoice3%==90 (set style=with cybernetic landscape)
if %rndChoice3%==91 (set style=with enchanted waterfall)
if %rndChoice3%==92 (set style=with floating ruins)
if %rndChoice3%==93 (set style=with mythical time travelers)
if %rndChoice3%==94 (set style=with neon-lit rain)
if %rndChoice3%==95 (set style=with magical underwater world)
if %rndChoice3%==96 (set style=with floating mountains)
if %rndChoice3%==97 (set style=with futuristic floating cities)
if %rndChoice3%==98 (set style=with enchanted mermaids)
if %rndChoice3%==99 (set style=with celestial waterfalls)
if %rndChoice3%==100 (set style=with icy ocean)
if %rndChoice3%==101 (set style=with futuristic space station)
if %rndChoice3%==102 (set style=with mythical flying beasts)


:: Construct the final prompt from the chosen keywords
set finalPrompt=photo of a %adjective% %subject% %style%

exit /b